cluster:
  name: k8s-cluster-a228

# 1. 數據傳送目的地對接 lgtm-system 下的微服務 API
destinations:
  - name: mimir
    type: prometheus
    url: "http://lgtm-components-mimir-nginx.lgtm-system.svc.cluster.local:80/api/v1/push"

  - name: loki
    type: loki
    url: "http://lgtm-components-loki-gateway.lgtm-system.svc.cluster.local:80/loki/api/v1/push"

  - name: tempo
    type: otlp
    protocol: http
    url: "http://lgtm-components-tempo-distributor.lgtm-system.svc.cluster.local:4318"

# 2. 採集功能與微收集器 (Alloy)
clusterMetrics:
  enabled: true

podLogs:
  enabled: true

clusterEvents:
  enabled: true

applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true

annotationAutodiscovery:
  enabled: true

alloy-receiver:
  enabled: true
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-logs:
  enabled: true

costMetrics:
  enabled: false
